WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        arrival:
            type: string
            length: '4'
        freeSeats:
            type: integer
            nullable: true
        pilot:
            type: string
            length: 255
            nullable: true
        takeofTime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: departures
        planeModel:
            targetEntity: WCS\CoavBundle\Entity\PlaneModel
        arrivals:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            inversedBy: arrival

